server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/plain, text/css, text/javascript, application/javascript, application/json
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:mariadb://${mariadb.host}:${mariadb.port}/${mariadb.database}
    username: ${mariadb.username}
    password: ${mariadb.password}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
