spring:
  datasource:
    url: jdbc:h2:mem:zip-code-db;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect