mariadb:
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  database: ${DATABASE_NAME:zipcode}
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT:3306}

server:
  port: 9191
  undertow:
    threads:
      worker: 34
      io: 2
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none